numPlots=0;
for io=26:49;
numPlots=numPlots+1;
end
numFigs = ceil(numPlots/3);

for fi=1:numFigs;
    figure
    for j=1:3;
    s=[0.10 0.65 0.5 0.25;...
    0.10 0.38 0.5 0.25;...
    0.10 0.11 0.5 0.25];

    plotNum = j + 3*(fi-1);
        if plotNum <= numPlots
            subplot(3,1,j)
            h=axesm('mapprojection','miller','geoid',referenceEllipsoid('wgs84'),...
            'MapLatLimit',[-3.9329 -1.8822],...
            'MapLonLimit',[-61.6249 -59.0311],...
            'frame','on','FEdgeColor',[0.1500 0.1500 0.1500],'FFaceColor','w',...
            'angleunits','degrees',...
            'LabelUnits','degrees','MLabelRound',-2,'PLabelRound',-2,...
            'fontname','helvetica',...
            'fontweight','bold',...
            'origin',[0 0 0],...
            'grid','on',...
            'parallellabel','on',...
            'meridianlabel','on',...
            'aspect','normal',...
            'flinewidth',1,...
            'fontsize',8,...
            'mlinelocation',1,...%%%intervalos entre longitudes
            'plinelocation',0.5);
            tightmap
            set(h,'visible','off')
            
		for io=26:49; %plotar variáveis
                cd G:\IgorCH4_matlab\IGOR_CH4\Programas\ADAM\2008.met13
                oz1=ncread('out2008met13.nc','o3');
                oz2=double(oz1(:,:,4,io));


                surfm(lat_w,lon_w,oz2.*1000); contourcmap('jet',0:1:60)
           
            end
        end
    end
end
